language: php
sudo: true
php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache/files
