name: Tests
on:
  push:
  schedule:
    - cron: "0 0 * * THU"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          version: 2
      - run: ./vendor/bin/phpunit
